#!/bin/sh -eu

cd "$(dirname "$0")"

nix shell \
    --ignore-environment \
    --file . \
    infra.np.nixpkgs-stable.shajra-nixos-rebuild \
    --command \
    shajra-nixos-rebuild \
    --nixos-rebuild "$(command -v nixos-rebuild)" \
    "$@"
